;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = tinyGS
data_dir = tinyGS/data

[env]
build_flags = 
 !python git_rev_macro.py
 -DMQTT_MAX_PACKET_SIZE=1000
 -DCORE_DEBUG_LEVEL=0
 -DIOTWEBCONF_DEBUG_DISABLED=0
 -DARDUINOJSON_USE_LONG_LONG=1
 ;lib_deps = https://github.com/jgromes/RadioLib/archive/refs/heads/master.zip
lib_deps = 
    improv/Improv@^1.2.4
    ;jgromes/RadioLib @ 7.6.0
    ;https://github.com/jgromes/RadioLib/archive/refs/heads/master.zip
    https://github.com/G4lile0/RadioLib.git
# Uncomment these 2 lines by deleting ";" and edit as needed to upload through OTA
;upload_protocol = espota
;upload_port = IP_OF_THE_BOARD

monitor_speed = 115200
upload_speed = 921600

; NOTE: There is no need to change anything below here, the board is configured through the Web panel
; Only make changes if you know what you are doing

[env:ESP32]
platform = espressif32 @ 6.10.0
board = heltec_wifi_lora_32
framework = arduino
board_build.flash_mode = dio
;board_build.partitions = default.csv
board_build.partitions = tinygs_4M_partition_table.csv

[env:ESP32-S3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = heltec_wifi_lora_32_V3
board_build.mcu = esp32s3
framework = arduino
board_build.partitions = tinygs_4M_partition_table.csv
monitor_rts = 0
monitor_dtr = 0

[env:ESP32-S3-USB]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = heltec_wifi_lora_32_V3
board_build.mcu = esp32s3
framework = arduino
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = tinygs_4M_partition_table.csv
monitor_rts = 1
monitor_dtr = 0

[env:ESP32-C3]
platform = espressif32 @ 6.10.0
board = esp32-c3-devkitm-1
; board_build.mcu = esp32c3
; board_build.f_cpu = 160000000L
framework = arduino
board_build.partitions = tinygs_4M_partition_table.csv

[env:ESP32-LILYGO_SX1280]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lilygo-t3-s3
board_build.mcu = esp32s3
framework = arduino
build_flags =
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
board_build.partitions = tinygs_4M_partition_table.csv

[env:lilygo-t-beam-supreme]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lilygo-t-beam-supreme
board_build.mcu = esp32s3
framework = arduino
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
board_build.partitions = tinygs_4M_partition_table.csv
lib_deps =
  ${env.lib_deps}
  mikalhart/TinyGPSPlus @ ^1.0.3
